### ISSUE TITLE
Error: WEAVIATE_API_KEY, WEAVIATE_URL, and WEAVIATE_INDEX_NAME must be set in the environment

### ISSUE THREAD

**Issue by dctmfoo** [langchain-ai/chat-langchainjs#17]
console.log(process.env.WEAVIATE_API_KEY); is printing the correct API key setup in /backend/.env file but still i get the below error. 

PS C:\Users\chat-langchainjs\backend> yarn build
CLI Building entry: src/chain.ts, src/constants.ts, src/ingest.ts, src/parser.ts, src/_index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.0.2
CLI Using tsup config: C:\Users\nags\chat-langchainjs\backend\tsup.config.js
CLI Target: es2021
CLI Cleaning output folder
ESM Build start
ESM dist\chain.js         33.00 B
ESM dist\constants.js     151.00 B
ESM dist\ingest.js        7.55 KB
ESM dist\parser.js        34.00 B
ESM dist\_index.js        3.75 KB
ESM dist\chain.js.map     71.00 B
ESM dist\constants.js.map 181.00 B
ESM dist\ingest.js.map    16.57 KB
ESM dist\parser.js.map    71.00 B
ESM dist\_index.js.map    8.69 KB
ESM ⚡️ Build success in 19ms
DTS Build start
DTS ⚡️ Build success in 2475ms
DTS dist\chain.d.ts     13.00 B
DTS dist\constants.d.ts 103.00 B
DTS dist\_index.d.ts    844.00 B
DTS dist\ingest.d.ts    13.00 B
DTS dist\parser.d.ts    13.00 B
PS C:\Users\chat-langchainjs\backend> yarn ingest
Failed to ingest docs
Error: WEAVIATE_API_KEY, WEAVIATE_URL, and WEAVIATE_INDEX_NAME must be set in the environment
    at ingestDocs (file:///C:/Users/nags/chat-langchainjs/backend/dist/ingest.js:176:11)
    at file:///C:/Users/nags/chat-langchainjs/backend/dist/ingest.js:256:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by bracesproul** [comment]
Hey @dctmfoo you need all three set, if you console log all three [directly above where that error is throwing](https://github.com/langchain-ai/chat-langchainjs/blob/main/backend/src/ingest.ts#L56) do they all log?

**Comment by bracesproul** [comment]
Hey @dctmfoo I'm going to close this issue as stale, if you're still experiencing it you may respond to this with more information and I can take another look.
Thank you
