### ISSUE TITLE
Not able to run the codebase locally.

### ISSUE THREAD

**Issue by sachanritik1** [langchain-ai/chat-langchainjs#34]
Upon running 'yarn ingest'  after building the backend. I get this error -

`Failed to ingest docs
Error: WEAVIATE_API_KEY, WEAVIATE_URL, and WEAVIATE_INDEX_NAME must be set in the environment
    at ingestDocs (file:///Users/ritiksachan/Desktop/chat-langchainjs/backend/dist/ingest.js:176:11)
    at file:///Users/ritiksachan/Desktop/chat-langchainjs/backend/dist/ingest.js:255:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)`

I guess it has something to do with the  WEAVIATE api key, url and index name. I have got the WEAVIATE api key, but not the url and index. 
Need some help setting this up.

**Comment by Mageenz** [comment]
Read the DEPLOYMENT.md file and follow the steps indicated in the file, which should help you
